gitlab:
  # If you want to use multiple group_ids use the seperated by commas '1234, 12345'
  enable: False
  api_url: 'https://gitlab.com/api/'
  api_version: 'v4'
  auth_token: ''
  group_ids: ''

gitlab_export:
  # Intended to be used with a tarfile of gitlab project export tarfiles
  enable: True
  export_directory: '/home/user/gitlab_export_backups'
  export_tarfile_path: '/home/user/tar_backup.tgz'
  
backup:
  # If no directory is specified for the backups it will perform create a backup folder in the working directory
  # of the script. 
  # If you don't want to store the cloned repos and delete them after backup change 'remove_directory' to False
  directory: '/home/user'
  remove_directory: False
  logfile_directory: '/home/user/backup_log.txt'
  # zip file backups:
  # If don't want to generate all repos as a zip change 'generate_zip_export' to False
  # If you don't want a limit on zip storage days leave this blank or set as 0
  generate_zip_export: True
  zip_export_directory: '/home/user'
  # Set this to the number of zip files you wish to store
  # If the amount of zips go past this number then the zips get deleted older to newest (based on date appended in the zip file name)
  zip_storage: 30
